config/routes.rb
Rails.application.routes.draw do
  get 'main/index'
  get '/instructions' => 'main#show_instructions'
  get '/:trap_id/requests' => 'main#show_requests'
  match '/:trap_id(/*other)', to: 'main#save_request', via: :all
  root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request_model.rb
class RequestModel < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index; end

  def save_request
    rqst = RequestModel.new
    rqst.trap_id = params[:trap_id]
    rqst.headers = headers.to_json
    rqst.cookies = cookies.to_json
    rqst.request_method = request.scheme
    rqst.query_string = request.env[:request_uri]
    rqst.remote_ip = request.ip
    rqst.query_string = request.original_fullpath
    rqst.request_method = request.request_method
    rqst.scheme_request = request.scheme
    rqst.query_params = params.to_json
    if rqst.save
      rendered_row = render_to_string'_table_row', locals: {app_request:rqst}, layout:false
      ActionCable.server.broadcast('r'+params[:trap_id], rendered_row)
    else
      render 'main/request_not_save', response_code: 500
    end
  end

  def show_requests
    @requests = RequestModel.where('trap_id = ?', params[:trap_id]).order('created_at desc')
    response.set_header('TRAP_ID', params[:trap_id])
  end

  def show_instructions; end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RequestsTrap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/_table_row.html.erb
<tr>
  <td><%= app_request.query_params %></td>
  <td><%= app_request.query_string %></td>
  <td><%= app_request.cookies %></td>
  <td><%= app_request.headers %></td>
  <td><%= app_request.scheme_request %></td>
  <td><%= app_request.request_method %></td>
  <td><%= app_request.remote_ip %></td>
  <td><%= app_request.created_at %></td>
</tr>

app/views/main/index.html.erb
<div class="container">
  <div class="title">REQUESTS-TRAP</div>
  <div class="link">
    <%= link_to "Instrunctions", instructions_path %>
  </div>
</div>

app/views/main/request_not_found.erb
<div class="container">
  <div class="title">No requests found</div>
  <div class="link">
    <%= link_to "Main page", main_index_path %>
    <%= link_to "Instrunctions", instructions_path %>
  </div>
</div>

app/views/main/request_not_save.erb
<div class="container">
  <div class="title">Сould not save request</div>
  <div class="link">
    <%= link_to "Main page", main_index_path %>
    <%= link_to "Instrunctions", instructions_path %>
  </div>
</div>

app/views/main/save_request.html.erb
<div class="container">
  <div class="title">Your request save</div>
  <div class="link">
    <%= link_to "Main page", main_index_path %>
    <%= link_to "Instrunctions", instructions_path %>
    <%= link_to "Show requests", (params[:trap_id])+'/requests' %>
  </div>
</div>

app/views/main/show_instructions.erb
<div class="container">
  <div class="instructions">
    <h3>Requests Trap: A tool for capture and display HTTP requests.</h3>

    <p>This simple tool is useful during the development of apps that
    integrate with external services, such as http clients, webhooks,
    etc. The Requests Trap app ('Req App') provides these services with
      an endpoint to which they can send requests and notifications.</p>

    <p>For example, let's assume we are developing an ecommerce site named
    “myshop" with PayPal integration. During development, Myshop can
      use Req App to see PayPal requests via a specific endpoint.</p>

    <p>If a Req App user gives this URL to the PayPal service:</p>
    <ul>

      <li>http://requests-trap.com/fireshop/aerhgewrh/serhsrt</li>

    <p>Then the user could see the IPN notifications sent by PayPal here:</p>

      <li>http://requests-trap.com/fireshop/requests</li>

    <p>The user can choose any url, all the requests made to that url can
    be viewed by anyone that knows the url, so he can use hard-to-guess
      urls to avoid that:</p>

    <li>http://requests-trap.com/mysupersecreturlxj34/requests</li>
    </ul>
  </div>
</div>

app/views/main/show_requests.html.erb
<div class="table-container">
  <h2>Requests with trap_id=<%= params[:trap_id] %></h2>
<table>
  <tr class="row-header">
    <th class="small-column">Query params</th>
    <th class="small-column">Query string</th>
    <th>Cookies</th>
    <th>Headers</th>
    <th class="small-column">Scheme</th>
    <th class="small-column">Request method</th>
    <th>Remote ip</th>
    <th>Request date</th>
  </tr>
  <% @requests.each do |app| %>
      <%= render "table_row", {app_request:app} %>
  <% end %>
</table>
  <% if @requests.length == 0 %>
    <h3 class="not-found">Requests not found</h3>
  <% end %>
</div>